import Head from "next/head";
import "./globals.css";
import { Rubik } from "next/font/google";
import './assets/css/tailwind.css'
import './assets/css/materialdesignicons.min.css'

const rubic = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-rubic",
});

export const metadata = {
  title: "Upwind - Next Js Landing Page Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="LTR" className="light scroll-smooth">
      <body className={`${rubic.variable} font-rubik !text-base !text-slate-900 dark:!text-white dark:!bg-slate-900`}>{children}</body>
    </html>
  );
}
